//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIDI.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MIDI.Localization.WizardResources", typeof(WizardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   音声 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Audio {
            get {
                return ResourceManager.GetString("Category_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム楽器 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_CustomInstruments {
            get {
                return ResourceManager.GetString("Category_CustomInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Debug {
            get {
                return ResourceManager.GetString("Category_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Effects {
            get {
                return ResourceManager.GetString("Category_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽器プリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_InstrumentPresets {
            get {
                return ResourceManager.GetString("Category_InstrumentPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_MIDI {
            get {
                return ResourceManager.GetString("Category_MIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パフォーマンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Performance {
            get {
                return ResourceManager.GetString("Category_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFZ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_SFZ {
            get {
                return ResourceManager.GetString("Category_SFZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoundFont に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_SoundFont {
            get {
                return ResourceManager.GetString("Category_SoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンセシス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category_Synthesis {
            get {
                return ResourceManager.GetString("Category_Synthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基準音A4（ラ）の周波数 (現代標準: 440Hz)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_A4Frequency {
            get {
                return ResourceManager.GetString("Description_A4Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計算によって残響を生成するリバーブの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_AlgorithmicReverb {
            get {
                return ResourceManager.GetString("Description_AlgorithmicReverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンチポップ適用時の最短アタック時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_AntiPopAttackSeconds {
            get {
                return ResourceManager.GetString("Description_AntiPopAttackSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンチポップ適用時の最短リリース時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_AntiPopReleaseSeconds {
            get {
                return ResourceManager.GetString("Description_AntiPopReleaseSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低音域の音量を調整します (倍率)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_BassGain {
            get {
                return ResourceManager.GetString("Description_BassGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音質を意図的に劣化させるエフェクトの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_BitCrusher {
            get {
                return ResourceManager.GetString("Description_BitCrusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一度に処理するサンプル数。小さいほど低遅延ですがCPU負荷が高く音飛びしやすくなります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_BufferSize {
            get {
                return ResourceManager.GetString("Description_BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原音と重ねる音の遅延時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ChorusDelay {
            get {
                return ResourceManager.GetString("Description_ChorusDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音の揺れの深さ。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ChorusDepth {
            get {
                return ResourceManager.GetString("Description_ChorusDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音を揺らす速さ（Hz）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ChorusRate {
            get {
                return ResourceManager.GetString("Description_ChorusRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原音に対するコーラス音の強さ (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ChorusStrength {
            get {
                return ResourceManager.GetString("Description_ChorusStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプレッサーが作動し始めるまでの時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_CompressionAttack {
            get {
                return ResourceManager.GetString("Description_CompressionAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   しきい値を超えた音を圧縮する比率 (例: 4)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_CompressionRatio {
            get {
                return ResourceManager.GetString("Description_CompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプレッサーが解除されるまでの時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_CompressionRelease {
            get {
                return ResourceManager.GetString("Description_CompressionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプレッサーが作動を開始する音量のしきい値 (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_CompressionThreshold {
            get {
                return ResourceManager.GetString("Description_CompressionThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音が鳴り始めてから最大音量に達するまでの時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultAttack {
            get {
                return ResourceManager.GetString("Description_DefaultAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大音量からサステインレベルまで減衰する時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultDecay {
            get {
                return ResourceManager.GetString("Description_DefaultDecay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートが離されてから音が消えるまでの時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultRelease {
            get {
                return ResourceManager.GetString("Description_DefaultRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが追加したSoundFontファイルを格納するディレクトリ。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultSoundFontDirectory {
            get {
                return ResourceManager.GetString("Description_DefaultSoundFontDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートが押されている間の音量レベル (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultSustain {
            get {
                return ResourceManager.GetString("Description_DefaultSustain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIファイルにテンポ情報がない場合のテンポ (120BPM = 500000)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultTempo {
            get {
                return ResourceManager.GetString("Description_DefaultTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音色の基本となる波形の種類。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DefaultWaveform {
            get {
                return ResourceManager.GetString("Description_DefaultWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やまびこの間隔（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_DelayTime {
            get {
                return ResourceManager.GetString("Description_DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音を歪ませるエフェクトの設定。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_Distortion {
            get {
                return ResourceManager.GetString("Description_Distortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノート開始/終了時に短いフェードを適用し、「プツッ」というノイズを低減します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableAntiPop {
            get {
                return ResourceManager.GetString("Description_EnableAntiPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エイリアシング（折り返しノイズ）を低減します。音質が向上しますがCPU負荷がわずかに増加します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableBandlimitedSynthesis {
            get {
                return ResourceManager.GetString("Description_EnableBandlimitedSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音をわずかに揺らして重ね、厚みと広がりを与えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableChorus {
            get {
                return ResourceManager.GetString("Description_EnableChorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量のばらつきを抑え、音圧を上げるエフェクトです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableCompression {
            get {
                return ResourceManager.GetString("Description_EnableCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インパルス応答(IR)ファイルを使用し、リアルな残響を再現します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableConvolutionReverb {
            get {
                return ResourceManager.GetString("Description_EnableConvolutionReverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声信号の直流成分を除去し、ノイズや歪みを防ぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableDCOffsetRemoval {
            get {
                return ResourceManager.GetString("Description_EnableDCOffsetRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのオーディオエフェクトの有効/無効を切り替えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableEffects {
            get {
                return ResourceManager.GetString("Description_EnableEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特定の周波数帯域を調整して音質を変えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableEqualizer {
            get {
                return ResourceManager.GetString("Description_EnableEqualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   短く周期的な遅延を用いて金属的なうねりを生み出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableFlanger {
            get {
                return ResourceManager.GetString("Description_EnableFlanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生終了時に音を滑らかに消し、突然の音切れを防ぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableGlobalFadeOut {
            get {
                return ResourceManager.GetString("Description_EnableGlobalFadeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPUを使用して高品質な畳み込みリバーブを処理します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableGpuConvolutionReverb {
            get {
                return ResourceManager.GetString("Description_EnableGpuConvolutionReverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPUを使用して複数のエフェクト（リバーブ、コンプなど）をまとめて処理します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableGpuEffectsChain {
            get {
                return ResourceManager.GetString("Description_EnableGpuEffectsChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPUを使用してイコライザー処理を行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableGpuEqualizer {
            get {
                return ResourceManager.GetString("Description_EnableGpuEqualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPUを使用して波形合成処理を行います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableGpuSynthesis {
            get {
                return ResourceManager.GetString("Description_EnableGpuSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量が一定値を超えないように制限し、音割れを防ぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableLimiter {
            get {
                return ResourceManager.GetString("Description_EnableLimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグインの動作ログをファイルに出力します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableLogging {
            get {
                return ResourceManager.GetString("Description_EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIファイル追加時にMIDIエディターを自動で開きます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableMidiEditor {
            get {
                return ResourceManager.GetString("Description_EnableMidiEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIキーボードからの入力を有効にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableMidiInput {
            get {
                return ResourceManager.GetString("Description_EnableMidiInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   外部連携用APIを有効にします。変更後はYMM4の再起動が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableNamedPipeApi {
            get {
                return ResourceManager.GetString("Description_EnableNamedPipeApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量を自動調整し、音割れを防ぎ均一化します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableNormalization {
            get {
                return ResourceManager.GetString("Description_EnableNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートの切り替わりをスムーズにし、ノイズを低減します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableNoteCrossfade {
            get {
                return ResourceManager.GetString("Description_EnableNoteCrossfade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マルチコアCPUを活用してレンダリングを高速化します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableParallelProcessing {
            get {
                return ResourceManager.GetString("Description_EnableParallelProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音の位相をずらして独特のうねりを生み出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnablePhaser {
            get {
                return ResourceManager.GetString("Description_EnablePhaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左右チャンネルで交互にやまびこ効果を生み出します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnablePingPongDelay {
            get {
                return ResourceManager.GetString("Description_EnablePingPongDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFZ形式のサンプラー音源を使用して再生します (有効な場合SoundFontより優先)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableSfz {
            get {
                return ResourceManager.GetString("Description_EnableSfz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoundFont (.sf2) ファイルを使用して再生します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnableSoundFont {
            get {
                return ResourceManager.GetString("Description_EnableSoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ADSRエンベロープの時間スケール。1より大きいと長く、小さいと短くなります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_EnvelopeScale {
            get {
                return ResourceManager.GetString("Description_EnvelopeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時に無視するMIDIチャンネル (カンマ区切り)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ExcludedChannels {
            get {
                return ResourceManager.GetString("Description_ExcludedChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時に無視するトラック番号 (カンマ区切り)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ExcludedTracks {
            get {
                return ResourceManager.GetString("Description_ExcludedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適切なSoundFontが見つからない場合、内蔵シンセサイザーで再生します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_FallbackToSynthesis {
            get {
                return ResourceManager.GetString("Description_FallbackToSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   やまびこが繰り返される強さ (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_Feedback {
            get {
                return ResourceManager.GetString("Description_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_FlangerDelay {
            get {
                return ResourceManager.GetString("Description_FlangerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   うねりの深さ (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_FlangerDepth {
            get {
                return ResourceManager.GetString("Description_FlangerDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   うねりの速さ（Hz）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_FlangerRate {
            get {
                return ResourceManager.GetString("Description_FlangerRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM合成における変調の深さ。大きいほど複雑な音色になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_FmModulationIndex {
            get {
                return ResourceManager.GetString("Description_FmModulationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM合成における変調波の周波数。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_FmModulatorFrequency {
            get {
                return ResourceManager.GetString("Description_FmModulatorFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェードアウトにかける時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_GlobalFadeOutSeconds {
            get {
                return ResourceManager.GetString("Description_GlobalFadeOutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用するインパルス応答ファイル (.wav) のパス。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ImpulseResponseFilePath {
            get {
                return ResourceManager.GetString("Description_ImpulseResponseFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YMM4起動時にGPUデバイスを初期化します。無効の場合、初回MIDI読み込み時に時間がかかることがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_InitializeGpuOnStartup {
            get {
                return ResourceManager.GetString("Description_InitializeGpuOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル読み込み時に最初に読み込む時間(秒)。長いほど開始は遅いが再生中の負荷が減ります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_InitialSyncDurationSeconds {
            get {
                return ResourceManager.GetString("Description_InitialSyncDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重ねて使用するSoundFontファイル (上から順に優先)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_Layers {
            get {
                return ResourceManager.GetString("Description_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量を制限する上限値 (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_LimiterThreshold {
            get {
                return ResourceManager.GetString("Description_LimiterThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイルの出力先パス。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_LogFilePath {
            get {
                return ResourceManager.GetString("Description_LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力するログの詳細度 (1:エラーのみ - 5:全て)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_LogLevel {
            get {
                return ResourceManager.GetString("Description_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体の音量を調整します。(0.0 - 1.0) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MasterVolume {
            get {
                return ResourceManager.GetString("Description_MasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成する音声の周波数の上限。これより高い周波数はクリップされます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MaxFrequency {
            get {
                return ResourceManager.GetString("Description_MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インパルス応答ファイルの最大読み込み時間（秒）。長いファイルはこの時間に切り詰められます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MaxImpulseResponseDurationSeconds {
            get {
                return ResourceManager.GetString("Description_MaxImpulseResponseDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイルの最大サイズ(KB)。超えると古いログから削除されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MaxLogSizeKB {
            get {
                return ResourceManager.GetString("Description_MaxLogSizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同時に再生できる最大ノート数。超えると古い音が消えることがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MaxPolyphony {
            get {
                return ResourceManager.GetString("Description_MaxPolyphony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並列処理に使用する最大スレッド数。通常はCPUコア数に合わせます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MaxThreads {
            get {
                return ResourceManager.GetString("Description_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中音域の音量を調整します (倍率)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MidGain {
            get {
                return ResourceManager.GetString("Description_MidGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用するMIDI入力デバイス名。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MidiInputDevice {
            get {
                return ResourceManager.GetString("Description_MidiInputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成する音声の周波数の下限。これより低い周波数はクリップされます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MinFrequency {
            get {
                return ResourceManager.GetString("Description_MinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これより小さいベロシティのノートは無視されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_MinVelocity {
            get {
                return ResourceManager.GetString("Description_MinVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化後の目標音量レベル (0.0 - 1.0)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_NormalizationLevel {
            get {
                return ResourceManager.GetString("Description_NormalizationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化が作動する音量のしきい値 (0.0 - 1.0)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_NormalizationThreshold {
            get {
                return ResourceManager.GetString("Description_NormalizationThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートクロスフェードの時間（秒）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_NoteCrossfadeDuration {
            get {
                return ResourceManager.GetString("Description_NoteCrossfadeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクト音を再度入力に戻す量 (0-1)。効果を強調します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_PhaserFeedback {
            get {
                return ResourceManager.GetString("Description_PhaserFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位相を変化させる速さ（Hz）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_PhaserRate {
            get {
                return ResourceManager.GetString("Description_PhaserRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェイザーのフィルター段数。多いほど複雑な効果になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_PhaserStages {
            get {
                return ResourceManager.GetString("Description_PhaserStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチベンドの変化範囲 (半音単位)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_PitchBendRange {
            get {
                return ResourceManager.GetString("Description_PitchBendRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ルールに一致しない場合に優先的に使用するSoundFontファイル名。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_PreferredSoundFont {
            get {
                return ResourceManager.GetString("Description_PreferredSoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボリュームやパンなどのコントロールチェンジを処理します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ProcessControlChanges {
            get {
                return ResourceManager.GetString("Description_ProcessControlChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチベンドメッセージを処理します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ProcessPitchBend {
            get {
                return ResourceManager.GetString("Description_ProcessPitchBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音色切り替えメッセージを処理します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ProcessProgramChanges {
            get {
                return ResourceManager.GetString("Description_ProcessProgramChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIプログラム番号とSFZファイルの関連付け。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ProgramMaps {
            get {
                return ResourceManager.GetString("Description_ProgramMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声レンダリング方法を選択。リアルタイムは低遅延だが品質が若干低下、GPUは対応ボードが必要。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_RenderingMode {
            get {
                return ResourceManager.GetString("Description_RenderingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIファイルの特性に応じて使用するSoundFontを決定するルール。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_Rules {
            get {
                return ResourceManager.GetString("Description_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1秒間に音声をサンプリングする回数。高いほど高音質ですがCPU負荷が増加します。(CD音質: 44100) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_SampleRate {
            get {
                return ResourceManager.GetString("Description_SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFZファイルを検索するフォルダのパス。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_SfzSearchPath {
            get {
                return ResourceManager.GetString("Description_SfzSearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIファイル追加時に内部情報ウィンドウを自動表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_ShowMidiInfoWindowOnLoad {
            get {
                return ResourceManager.GetString("Description_ShowMidiInfoWindowOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高音域の音量を調整します (倍率)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_TrebleGain {
            get {
                return ResourceManager.GetString("Description_TrebleGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プラグイン同梱のデフォルトSoundFont (GeneralUser-GS.sf2) を使用します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_UseDefaultSoundFont {
            get {
                return ResourceManager.GetString("Description_UseDefaultSoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   より詳細なログ（例外スタックトレースなど）を出力します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_VerboseLogging {
            get {
                return ResourceManager.GetString("Description_VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー定義のWAVファイルを配置するフォルダ。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_WavetableDirectory {
            get {
                return ResourceManager.GetString("Description_WavetableDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原音(Dry)とエフェクト音(Wet)のバランス (0-1)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Description_WetDryMix {
            get {
                return ResourceManager.GetString("Description_WetDryMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A4周波数 (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_A4Frequency {
            get {
                return ResourceManager.GetString("Setting_A4Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アルゴリズミックリバーブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_AlgorithmicReverb {
            get {
                return ResourceManager.GetString("Setting_AlgorithmicReverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振幅エンベロープ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_AmplitudeEnvelope {
            get {
                return ResourceManager.GetString("Setting_AmplitudeEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振幅LFO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_AmplitudeLfo {
            get {
                return ResourceManager.GetString("Setting_AmplitudeLfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンチポップ アタック (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_AntiPopAttackSeconds {
            get {
                return ResourceManager.GetString("Setting_AntiPopAttackSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンチポップ リリース (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_AntiPopReleaseSeconds {
            get {
                return ResourceManager.GetString("Setting_AntiPopReleaseSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アタック (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Attack {
            get {
                return ResourceManager.GetString("Setting_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   低音ゲイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_BassGain {
            get {
                return ResourceManager.GetString("Setting_BassGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビットクラッシャー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_BitCrusher {
            get {
                return ResourceManager.GetString("Setting_BitCrusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ビット深度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_BitDepth {
            get {
                return ResourceManager.GetString("Setting_BitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッファサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_BufferSize {
            get {
                return ResourceManager.GetString("Setting_BufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コーラス ディレイ (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ChorusDelay {
            get {
                return ResourceManager.GetString("Setting_ChorusDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コーラス 深さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ChorusDepth {
            get {
                return ResourceManager.GetString("Setting_ChorusDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コーラス レート (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ChorusRate {
            get {
                return ResourceManager.GetString("Setting_ChorusRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コーラス 強度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ChorusStrength {
            get {
                return ResourceManager.GetString("Setting_ChorusStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプ アタック (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_CompressionAttack {
            get {
                return ResourceManager.GetString("Setting_CompressionAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプ レシオ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_CompressionRatio {
            get {
                return ResourceManager.GetString("Setting_CompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプ リリース (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_CompressionRelease {
            get {
                return ResourceManager.GetString("Setting_CompressionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプ 閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_CompressionThreshold {
            get {
                return ResourceManager.GetString("Setting_CompressionThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム楽器 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_CustomInstruments {
            get {
                return ResourceManager.GetString("Setting_CustomInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カットオフ (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Cutoff {
            get {
                return ResourceManager.GetString("Setting_Cutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   減衰 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Damping {
            get {
                return ResourceManager.GetString("Setting_Damping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディケイ (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Decay {
            get {
                return ResourceManager.GetString("Setting_Decay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト アタック (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultAttack {
            get {
                return ResourceManager.GetString("Setting_DefaultAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト ディケイ (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultDecay {
            get {
                return ResourceManager.GetString("Setting_DefaultDecay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト リリース (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultRelease {
            get {
                return ResourceManager.GetString("Setting_DefaultRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoundFontディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultSoundFontDirectory {
            get {
                return ResourceManager.GetString("Setting_DefaultSoundFontDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト サステイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultSustain {
            get {
                return ResourceManager.GetString("Setting_DefaultSustain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルトテンポ (μs/拍) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultTempo {
            get {
                return ResourceManager.GetString("Setting_DefaultTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト波形 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DefaultWaveform {
            get {
                return ResourceManager.GetString("Setting_DefaultWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレイタイム (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DelayTime {
            get {
                return ResourceManager.GetString("Setting_DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   深さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Depth {
            get {
                return ResourceManager.GetString("Setting_Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディストーション設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Distortion {
            get {
                return ResourceManager.GetString("Setting_Distortion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドライブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Drive {
            get {
                return ResourceManager.GetString("Setting_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドライレベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_DryLevel {
            get {
                return ResourceManager.GetString("Setting_DryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Enable {
            get {
                return ResourceManager.GetString("Setting_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンチポップを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableAntiPop {
            get {
                return ResourceManager.GetString("Setting_EnableAntiPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バンドリミテッド合成を有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableBandlimitedSynthesis {
            get {
                return ResourceManager.GetString("Setting_EnableBandlimitedSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コーラスを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableChorus {
            get {
                return ResourceManager.GetString("Setting_EnableChorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンプレッサーを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableCompression {
            get {
                return ResourceManager.GetString("Setting_EnableCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   畳み込みリバーブを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableConvolutionReverb {
            get {
                return ResourceManager.GetString("Setting_EnableConvolutionReverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DCオフセット除去を有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableDCOffsetRemoval {
            get {
                return ResourceManager.GetString("Setting_EnableDCOffsetRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクトを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableEffects {
            get {
                return ResourceManager.GetString("Setting_EnableEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イコライザーを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableEqualizer {
            get {
                return ResourceManager.GetString("Setting_EnableEqualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フランジャーを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableFlanger {
            get {
                return ResourceManager.GetString("Setting_EnableFlanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グローバルフェードアウトを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableGlobalFadeOut {
            get {
                return ResourceManager.GetString("Setting_EnableGlobalFadeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   畳み込みリバーブ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableGpuConvolutionReverb {
            get {
                return ResourceManager.GetString("Setting_EnableGpuConvolutionReverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エフェクトチェーン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableGpuEffectsChain {
            get {
                return ResourceManager.GetString("Setting_EnableGpuEffectsChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イコライザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableGpuEqualizer {
            get {
                return ResourceManager.GetString("Setting_EnableGpuEqualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンセシス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableGpuSynthesis {
            get {
                return ResourceManager.GetString("Setting_EnableGpuSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リミッターを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableLimiter {
            get {
                return ResourceManager.GetString("Setting_EnableLimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableLogging {
            get {
                return ResourceManager.GetString("Setting_EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDIエディターを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableMidiEditor {
            get {
                return ResourceManager.GetString("Setting_EnableMidiEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI入力を有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableMidiInput {
            get {
                return ResourceManager.GetString("Setting_EnableMidiInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前付きパイプAPIを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableNamedPipeApi {
            get {
                return ResourceManager.GetString("Setting_EnableNamedPipeApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化を有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableNormalization {
            get {
                return ResourceManager.GetString("Setting_EnableNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ノートクロスフェードを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableNoteCrossfade {
            get {
                return ResourceManager.GetString("Setting_EnableNoteCrossfade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並列処理を有効にする (CPU) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableParallelProcessing {
            get {
                return ResourceManager.GetString("Setting_EnableParallelProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェイザーを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnablePhaser {
            get {
                return ResourceManager.GetString("Setting_EnablePhaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピンポンディレイを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnablePingPongDelay {
            get {
                return ResourceManager.GetString("Setting_EnablePingPongDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFZを有効にする (SoundFontより優先) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableSfz {
            get {
                return ResourceManager.GetString("Setting_EnableSfz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoundFontを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnableSoundFont {
            get {
                return ResourceManager.GetString("Setting_EnableSoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了プログラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EndProgram {
            get {
                return ResourceManager.GetString("Setting_EndProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンベロープスケール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EnvelopeScale {
            get {
                return ResourceManager.GetString("Setting_EnvelopeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イコライザー設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_EQ {
            get {
                return ResourceManager.GetString("Setting_EQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   除外チャンネル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ExcludedChannels {
            get {
                return ResourceManager.GetString("Setting_ExcludedChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   除外トラック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ExcludedTracks {
            get {
                return ResourceManager.GetString("Setting_ExcludedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シンセシスへフォールバック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FallbackToSynthesis {
            get {
                return ResourceManager.GetString("Setting_FallbackToSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィードバック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Feedback {
            get {
                return ResourceManager.GetString("Setting_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Filter {
            get {
                return ResourceManager.GetString("Setting_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルターLFO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FilterLfo {
            get {
                return ResourceManager.GetString("Setting_FilterLfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フランジャー ディレイ (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FlangerDelay {
            get {
                return ResourceManager.GetString("Setting_FlangerDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フランジャー 深さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FlangerDepth {
            get {
                return ResourceManager.GetString("Setting_FlangerDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フランジャー レート (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FlangerRate {
            get {
                return ResourceManager.GetString("Setting_FlangerRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM 変調指数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FmModulationIndex {
            get {
                return ResourceManager.GetString("Setting_FmModulationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FM 変調周波数 (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_FmModulatorFrequency {
            get {
                return ResourceManager.GetString("Setting_FmModulatorFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェードアウト時間 (秒) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_GlobalFadeOutSeconds {
            get {
                return ResourceManager.GetString("Setting_GlobalFadeOutSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IRファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ImpulseResponseFilePath {
            get {
                return ResourceManager.GetString("Setting_ImpulseResponseFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時にGPUを初期化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_InitializeGpuOnStartup {
            get {
                return ResourceManager.GetString("Setting_InitializeGpuOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期読み込み時間 (秒) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_InitialSyncDurationSeconds {
            get {
                return ResourceManager.GetString("Setting_InitialSyncDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   楽器プリセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_InstrumentPresets {
            get {
                return ResourceManager.GetString("Setting_InstrumentPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoundFontレイヤー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Layers {
            get {
                return ResourceManager.GetString("Setting_Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LFO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Lfo {
            get {
                return ResourceManager.GetString("Setting_Lfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リミッター 閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_LimiterThreshold {
            get {
                return ResourceManager.GetString("Setting_LimiterThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_LogFilePath {
            get {
                return ResourceManager.GetString("Setting_LogFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログレベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_LogLevel {
            get {
                return ResourceManager.GetString("Setting_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスターボリューム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MasterVolume {
            get {
                return ResourceManager.GetString("Setting_MasterVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大周波数 (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MaxFrequency {
            get {
                return ResourceManager.GetString("Setting_MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IR最大読み込み時間 (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MaxImpulseResponseDurationSeconds {
            get {
                return ResourceManager.GetString("Setting_MaxImpulseResponseDurationSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大ログサイズ (KB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MaxLogSizeKB {
            get {
                return ResourceManager.GetString("Setting_MaxLogSizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大同時発音数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MaxPolyphony {
            get {
                return ResourceManager.GetString("Setting_MaxPolyphony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大スレッド数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MaxThreads {
            get {
                return ResourceManager.GetString("Setting_MaxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中音ゲイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MidGain {
            get {
                return ResourceManager.GetString("Setting_MidGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI入力デバイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MidiInputDevice {
            get {
                return ResourceManager.GetString("Setting_MidiInputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小周波数 (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MinFrequency {
            get {
                return ResourceManager.GetString("Setting_MinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最小ベロシティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_MinVelocity {
            get {
                return ResourceManager.GetString("Setting_MinVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミックス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Mix {
            get {
                return ResourceManager.GetString("Setting_Mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Name {
            get {
                return ResourceManager.GetString("Setting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化 レベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_NormalizationLevel {
            get {
                return ResourceManager.GetString("Setting_NormalizationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規化 閾値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_NormalizationThreshold {
            get {
                return ResourceManager.GetString("Setting_NormalizationThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クロスフェード時間 (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_NoteCrossfadeDuration {
            get {
                return ResourceManager.GetString("Setting_NoteCrossfadeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェイザー フィードバック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_PhaserFeedback {
            get {
                return ResourceManager.GetString("Setting_PhaserFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェイザー レート (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_PhaserRate {
            get {
                return ResourceManager.GetString("Setting_PhaserRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フェイザー ステージ数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_PhaserStages {
            get {
                return ResourceManager.GetString("Setting_PhaserStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチベンド範囲 (半音) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_PitchBendRange {
            get {
                return ResourceManager.GetString("Setting_PitchBendRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチLFO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_PitchLfo {
            get {
                return ResourceManager.GetString("Setting_PitchLfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   優先SoundFontファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_PreferredSoundFont {
            get {
                return ResourceManager.GetString("Setting_PreferredSoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールチェンジを処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ProcessControlChanges {
            get {
                return ResourceManager.GetString("Setting_ProcessControlChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ピッチベンドを処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ProcessPitchBend {
            get {
                return ResourceManager.GetString("Setting_ProcessPitchBend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムチェンジを処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ProcessProgramChanges {
            get {
                return ResourceManager.GetString("Setting_ProcessProgramChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Program {
            get {
                return ResourceManager.GetString("Setting_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFZ プログラムマップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ProgramMaps {
            get {
                return ResourceManager.GetString("Setting_ProgramMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レート (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Rate {
            get {
                return ResourceManager.GetString("Setting_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レート削減 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_RateReduction {
            get {
                return ResourceManager.GetString("Setting_RateReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リリース (s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Release {
            get {
                return ResourceManager.GetString("Setting_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レンダリングモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_RenderingMode {
            get {
                return ResourceManager.GetString("Setting_RenderingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レゾナンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Resonance {
            get {
                return ResourceManager.GetString("Setting_Resonance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部屋の広さ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_RoomSize {
            get {
                return ResourceManager.GetString("Setting_RoomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SoundFontルール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Rules {
            get {
                return ResourceManager.GetString("Setting_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サンプルレート (Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_SampleRate {
            get {
                return ResourceManager.GetString("Setting_SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SFZ 検索フォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_SfzSearchPath {
            get {
                return ResourceManager.GetString("Setting_SfzSearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIDI情報ウィンドウを表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_ShowMidiInfoWindowOnLoad {
            get {
                return ResourceManager.GetString("Setting_ShowMidiInfoWindowOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始プログラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_StartProgram {
            get {
                return ResourceManager.GetString("Setting_StartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サステイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Sustain {
            get {
                return ResourceManager.GetString("Setting_Sustain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   高音ゲイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_TrebleGain {
            get {
                return ResourceManager.GetString("Setting_TrebleGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   種類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Type {
            get {
                return ResourceManager.GetString("Setting_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルトSoundFontを使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_UseDefaultSoundFont {
            get {
                return ResourceManager.GetString("Setting_UseDefaultSoundFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wavetableファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_UserWavetableFile {
            get {
                return ResourceManager.GetString("Setting_UserWavetableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細ログを有効にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_VerboseLogging {
            get {
                return ResourceManager.GetString("Setting_VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Volume {
            get {
                return ResourceManager.GetString("Setting_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   波形 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Waveform {
            get {
                return ResourceManager.GetString("Setting_Waveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wavetableフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_WavetableDirectory {
            get {
                return ResourceManager.GetString("Setting_WavetableDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_WetDryMix {
            get {
                return ResourceManager.GetString("Setting_WetDryMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウェットレベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_WetLevel {
            get {
                return ResourceManager.GetString("Setting_WetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   広がり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setting_Width {
            get {
                return ResourceManager.GetString("Setting_Width", resourceCulture);
            }
        }
    }
}
